// Generates the Slack app manifests from the tool definitions so the requested
// OAuth scopes can never drift from what the tools actually call.
//
//   bun scripts/gen-manifests.ts            # write manifest.{full,readonly}.yaml
//   bun scripts/gen-manifests.ts --check    # exit 1 if either file is out of sync
import { readFileSync, writeFileSync } from "node:fs"

import { allTools, readTools } from "../packages/slack-core/src/registry"
import type { SlackTool } from "../packages/slack-core/src/types"

const ROOT = new URL("..", import.meta.url).pathname

const uniq = (tools: SlackTool[]) => [...new Set(tools.flatMap((t) => t.scopes))].sort()
const readScopes = uniq(readTools)
const fullScopes = uniq(allTools)
const writeScopes = fullScopes.filter((s) => !readScopes.includes(s))

const list = (scopes: string[]) => scopes.map((s) => `      - ${s}`).join("\n")

const readonly = `# Slack app manifest: better-slack-mcp (read only, user token / xoxp), least privilege
#
# Generated by scripts/gen-manifests.ts from the read tools in packages/slack-core.
# Do not edit by hand; run "bun gen:manifests" after changing tool scopes.
#
# Create the app:  api.slack.com/apps  ->  Create New App  ->  From a manifest
#                  -> paste -> Create -> Install -> copy the "User OAuth Token".
display_information:
  name: better-slack-mcp (read-only)
  description: Read-only personal Slack MCP server (user token)
  background_color: "#0b1221"
oauth_config:
  scopes:
    user:
${list(readScopes)}
settings:
  org_deploy_enabled: true
  socket_mode_enabled: false
  token_rotation_enabled: false
`

const full = `# Slack app manifest: better-slack-mcp (full: read + write, user token / xoxp)
#
# Generated by scripts/gen-manifests.ts from the tools in packages/slack-core.
# Do not edit by hand; run "bun gen:manifests" after changing tool scopes.
#
# Create the app:  api.slack.com/apps  ->  Create New App  ->  From a manifest
#                  -> paste this file -> Create -> Install to Workspace
#                  -> copy the "User OAuth Token" (xoxp-...) into SLACK_MCP_XOXP_TOKEN.
#
# For a read-only install use manifest.readonly.yaml instead.
display_information:
  name: better-slack-mcp
  description: Personal, per-workspace Slack MCP server (user token)
  background_color: "#0b1221"
oauth_config:
  scopes:
    user:
      # read tools
${list(readScopes)}
      # write tools
${list(writeScopes)}
settings:
  org_deploy_enabled: true
  socket_mode_enabled: false
  token_rotation_enabled: false
`

const files: ReadonlyArray<readonly [string, string]> = [
  [`${ROOT}manifest.readonly.yaml`, readonly],
  [`${ROOT}manifest.full.yaml`, full],
]

if (import.meta.main) {
  const check = process.argv.includes("--check")
  let drift = false
  for (const [path, content] of files) {
    if (check) {
      const onDisk = readFileSync(path, "utf8")
      if (onDisk !== content) {
        drift = true
        console.error(`out of sync: ${path}`)
      }
    } else {
      writeFileSync(path, content)
      console.log(`wrote ${path}`)
    }
  }
  if (check && drift) {
    console.error('manifests are out of sync with the tools; run "bun gen:manifests"')
    process.exit(1)
  }
  if (check) console.log("manifests in sync")
}

export { fullScopes, readScopes, writeScopes }
