// Generates README.md and docs/coverage.md from the committed Slack method
// snapshot (scripts/slack-methods.json) and the tool registry, so the coverage
// tables can never drift from the tools.
//
//   bun scripts/gen-docs.ts            # write README.md + docs/coverage.md
//   bun scripts/gen-docs.ts --check    # exit 1 if either file is out of sync
import { mkdirSync, readFileSync, writeFileSync } from "node:fs"

import { allTools, toolByName } from "../packages/slack-core/src/registry"
import rawMethods from "./slack-methods.json"

const methods = rawMethods as Array<{ method: string; userScopes: string[] }>
const ROOT = new URL("..", import.meta.url).pathname

const code = (v: string) => "`" + v + "`"
// method -> our tool name: dots to underscores, camelCase segments to snake_case
const toSnake = (m: string) =>
  m
    .replace(/\./g, "_")
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .toLowerCase()
const isImplemented = (m: string) => Boolean(toolByName(toSnake(m)))

const methodLink = (m: string) => `[${code(m)}](https://docs.slack.dev/reference/methods/${m})`
const scopeLink = (s: string) =>
  `[${code(s)}](https://docs.slack.dev/reference/scopes/${s.replaceAll(":", ".")})`
const scopeCell = (userScopes: string[]) =>
  userScopes.length ? userScopes.map(scopeLink).join(" · ") : code("-")
const row = (m: { method: string; userScopes: string[] }) =>
  `| ${methodLink(m.method)} | ${isImplemented(m.method) ? code(toSnake(m.method)) : code("-")} | ${scopeCell(m.userScopes)} |`

const methodSnakes = new Set(methods.map((m) => toSnake(m.method)))
const composites = allTools.filter((t) => !methodSnakes.has(t.name)).map((t) => t.name)
const implementedCount = methods.filter((m) => isImplemented(m.method)).length

const header = "| slack api | better-slack-mcp | user token scopes |\n| --- | --- | --- |"
const doneRows = methods
  .filter((m) => isImplemented(m.method))
  .map(row)
  .join("\n")
const allRows = methods.map(row).join("\n")

const legend =
  "**better-slack-mcp** is our tool name (names mirror the method, snake_cased; `-` = not yet implemented). **user token scopes** are the OAuth scopes a user token (`xoxp`) needs, per the linked [method](https://docs.slack.dev/reference/methods/) and [scope](https://docs.slack.dev/reference/scopes/) pages (`-` = none listed; the method is bot/app-only or needs no scope)."

const compositeLine = `${implementedCount} methods covered 1:1, plus ${composites.length} composite tools that wrap no single method: ${composites.map(code).join(", ")} (${allTools.length} tools total).`

const banner =
  "<!-- Generated by scripts/gen-docs.ts from the tool registry. Do not edit; run `bun gen:docs`. -->\n\n"

const readme = `${banner}# better-slack-mcp

A user-token (xoxp) Slack MCP server. Tools mirror the Slack Web API.

## Installation

1. Create a Slack app from a manifest: [api.slack.com/apps](https://api.slack.com/apps) -> **Create New App** -> **From a manifest**.
2. Paste [\`manifest.readonly.yaml\`](manifest.readonly.yaml) for read-only access, or [\`manifest.full.yaml\`](manifest.full.yaml) for read + write. Each requests exactly the scopes the tools below use (generated by \`bun gen:manifests\`).
3. **Install to Workspace**, then copy the **User OAuth Token** (\`xoxp-...\`).
4. Provide it to the server as \`SLACK_MCP_XOXP_TOKEN\`:

\`\`\`sh
export SLACK_MCP_XOXP_TOKEN=xoxp-your-token
\`\`\`

> The stdio MCP server that hosts these tools ships in the next milestone (M2); this package is the tool layer it wraps.

## Implemented tools

${legend}

${compositeLine}

${header}
${doneRows}

See [docs/coverage.md](docs/coverage.md) for the full non-admin Slack Web API surface (${methods.length} methods), and the [roadmap](docs/ROADMAP.md) for milestones.
`

const coverage = `${banner}# Slack Web API coverage

All ${methods.length} non-admin methods, in [reference](https://docs.slack.dev/reference/methods/) order.

${legend}

${header}
${allRows}
`

export const buildDocs = () => ({ readme, coverage })

const files: ReadonlyArray<readonly [string, string]> = [
  [`${ROOT}README.md`, readme],
  [`${ROOT}docs/coverage.md`, coverage],
]

if (import.meta.main) {
  const check = process.argv.includes("--check")
  let drift = false
  mkdirSync(`${ROOT}docs`, { recursive: true })
  for (const [path, content] of files) {
    if (check) {
      if (readFileSync(path, "utf8") !== content) {
        drift = true
        console.error(`out of sync: ${path}`)
      }
    } else {
      writeFileSync(path, content)
      console.log(`wrote ${path}`)
    }
  }
  if (check && drift) {
    console.error('docs are out of sync with the tools; run "bun gen:docs"')
    process.exit(1)
  }
  if (check) console.log("docs in sync")
}
